.row
  #logo
  .col-sm-12.col-md-6
    h2 Welcome to doodoo
    p DooDoo will help you manage your aims.
    .list-group
      a.list-group-item.list-group-item-action target="_blank" href="https://docs.amberframework.org" Getting Started with Amber Framework
      a.list-group-item.list-group-item-action target="_blank" href="https://github.com/veelenga/awesome-crystal" List of Awesome Crystal projects and shards
      a.list-group-item.list-group-item-action target="_blank" href="https://crystalshards.xyz" What's hot in Crystal right now
      a.list-group-item.list-group-item-action target="_blank" href="/todos" Todos
